// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdquLKLlKnFZMB7M2g4unTQtNz18srwvM',
    appId: '1:593007484385:web:54dedd4eff3e82850046a0',
    messagingSenderId: '593007484385',
    projectId: 'rehla-driver',
    authDomain: 'rehla-driver.firebaseapp.com',
    storageBucket: 'rehla-driver.appspot.com',
    measurementId: 'G-QTJZ9C8927',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-2P4JRB966lNswS9NZin619OHTVit1Sw',
    appId: '1:593007484385:android:746231e7d6df5df90046a0',
    messagingSenderId: '593007484385',
    projectId: 'rehla-driver',
    storageBucket: 'rehla-driver.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlAHpvAnBuhXVHWe-17j9HRTxfxlUgcko',
    appId: '1:593007484385:ios:2a8aaa3cb18d38260046a0',
    messagingSenderId: '593007484385',
    projectId: 'rehla-driver',
    storageBucket: 'rehla-driver.appspot.com',
    iosClientId: '593007484385-uh03qkp8f61i4if8v084mt15fqed84a2.apps.googleusercontent.com',
    iosBundleId: 'com.example.rehlaDriver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlAHpvAnBuhXVHWe-17j9HRTxfxlUgcko',
    appId: '1:593007484385:ios:6eeb94b93518e7100046a0',
    messagingSenderId: '593007484385',
    projectId: 'rehla-driver',
    storageBucket: 'rehla-driver.appspot.com',
    iosClientId: '593007484385-26pbk6l65uftcl174qsi7koqq2ms6s4g.apps.googleusercontent.com',
    iosBundleId: 'com.example.rehlaDriver.RunnerTests',
  );
}
