import 'package:sarahah_questions/app/localization/trans_manager.dart';

class Ar {
  static final Ar singleton = Ar._internal();
  Ar._internal();

  Map<String, String> get keys => {
        TransManager.thereIsNoOptionsFound: "لا توجد خيارات متاحة",
        TransManager.loading: "جار التحميل...",
        TransManager.login: "تسجيل الدخول",
        TransManager.username: "اسم المستخدم",
        TransManager.password: "كلمة المرور",
        TransManager.dontHaveRehlaAccount: "ليس لديك حساب على رحلة؟",
        TransManager.createNewAccount: "إنشاء حساب",
        TransManager.rememberMe: "تذكرني",
        TransManager.forgotPassword: "هل نسيت كلمة المرور؟",
        TransManager.firstName: "الاسم الأول",
        TransManager.middleName: "اسم الأب",
        TransManager.lastName: "اسم العائلة",
        TransManager.phoneNumber: "رقم الهاتف",
        TransManager.next: "التالي",
        TransManager.iHaveRehlaAccount: "لدي حساب على رحلة",
        TransManager.dateOfBirth: "تاريخ الميلاد",
        TransManager.selectDateOfBirth: "اختر تاريخ الميلاد",
        TransManager.gender: "الجنس",
        TransManager.selectYourGender: "اختر جنسك",
        TransManager.idNumber: "رقم الهوية",
        TransManager.drivingLicenseNumber: "رقم رخصة القيادة",
        TransManager.carNumber: "رقم السيارة",
        TransManager.carBrand: "ماركة السيارة",
        TransManager.selectCarBrand: "اختر ماركة السيارة",
        TransManager.carModel: "موديل السيارة",
        TransManager.selectCarModel: "اختر موديل السيارة",
        TransManager.carColor: "لون السيارة",
        TransManager.selectCarColor: "اختر لون السيارة",
        TransManager.emailAddress: "عنوان البريد الإلكتروني",
        TransManager.personalPicture: "الصورة الشخصية",
        TransManager.idPhoto: "صورة الهوية",
        TransManager.uploadAphotoOfYourId: "تحميل صورة للهوية",
        TransManager.drivingLicenseImage: "صورة رخصة القيادة",
        TransManager.uploadAphotoOfYourDrivingLicense:
            "تحميل صورة لرخصة القيادة",
        TransManager.enterYourFirstName: "أدخل اسمك الأول",
        TransManager.middleNameIsRequired: "اسم الأب مطلوب",
        TransManager.enterYourLastName: "أدخل اسم العائلة",
        TransManager.invalidPhoneNumber: "رقم هاتف غير صالح",
        TransManager.gallery: "المعرض",
        TransManager.camera: "الكاميرا",
        TransManager.pickImage: "اختر صورة",
        TransManager.invalidEmail: "عنوان البريد الإلكتروني غير صالح",
        TransManager.weakPassword: "كلمة المرور ضعيفة",
        TransManager.invalidUsername: "اسم المستخدم غير صالح",
        TransManager.resetPassword: "إعادة تعيين كلمة المرور",
        TransManager.resetPasswordHintPart1:
            "الرجاء كتابة البريد الإلكتروني الخاص بحسابك, لإستكمال إجراء ",
        TransManager.resetPasswordHintPart2: "تغيير كلمة المرور ",
        TransManager.resetPasswordHintPart3: " ",
        TransManager.continue_: "متابعة",
        TransManager.iHaveRememberedMyPassword: "تذكرت كلمة المرور الخاصة بي",
        TransManager.pleaseWait: "الرجاء الانتظار...",
        TransManager.verifyIdentity: "تأكيد الهوية",
        TransManager.verifyIdentityHintPart1:
            "الرجاء كتابة الكود المرسل عبر البريد الإلكتروني الخاص بك المكون  من ",
        TransManager.verifyIdentityHintPart2: "6 أرقام ",
        TransManager.verifyIdentityHintPart3: "بشكل صحيح",
        TransManager.resendCode: "إعادة إرسال الكود",
        TransManager.createNewPassword: "تعيين كلمة مرور جديدة",
        TransManager.createNewPasswordHintPart1:
            "أنشئ كلمة مرور جديدة, عادةً ما تتكون كلمة المرور من ",
        TransManager.createNewPasswordHintPart2: "8 خانات ",
        TransManager.createNewPasswordHintPart3:
            "على الأقل. للمعلومية كلمة المرور القوية هي مزيج من الأحرف والرموز والأرقام",
        TransManager.newPassword: "كلمة المرور الجديدة",
        TransManager.confirmNewPassword: "تأكيد كلمة المرور الجديدة",
        TransManager.yourNewPasswordHasBeenSetSuccessfully:
            "تمت عملية تعين كلمة المرور الجديدة بنجاح",
        TransManager.thisFieldRequired: "هذا الحقل مطلوب",
        TransManager.underReview: "قيد المراجعة",
        TransManager.accountUnderReviewHint:
            "الحساب الخاص بك قيد المراجعة ، بمجرد الإنتهاء سنوافيك بكامل التفاصيل,\n نتمنى لك يوماً سعيداً",
        TransManager.congratulations: "تهانينا",
        TransManager.accountAcceptedHint:
            "تم قبول حسابك على منصة رحلة, أنت تتمتع اللآن بكامل الصلاحيات على حسابك.",
        TransManager.sorry: "المعذرة!",
        TransManager.accountRejectedHint:
            "تم رفض حسابك على منصة رحلة, راجع سبب الرفض المرسل إليك",
        TransManager.male: "ذكر",
        TransManager.female: "أنثى",
        TransManager.twoPasswordsDoesNotMatch: "كلمتي المرور غير متطابقتين",
        TransManager.pleaseEnterValidEmail: "الرجاء إدخال بريد إلكتروني صالح",
        TransManager.requiredField: "هذا الحقل مطلوب",
        TransManager.passwordMustBeAtLeast6Characters:
            "كلمة المرور يجب أن تكون على الأقل 6 أحرف",
        TransManager.pleaseEnterValidId: "الرجاء إدخال رقم هوية صالح",
        TransManager.pleaseEnterValidDateOfBirth:
            "الرجاء إدخال تاريخ ميلاد صالح",
        TransManager.pleaseEnterValidName: "الرجاء إدخال اسم صالح",
        TransManager.pleaseEnterValidMobile: "الرجاء إدخال رقم هاتف صالح",
        TransManager.pleaseEnterValidEmailOrMobile:
            "الرجاء ادخال بريد إلكتروني أو رقم هاتف صالح",
        TransManager.pleaseEnterValidLink: "الرجاء إدخال رابط صالح",
        TransManager.myWallet : "محفظتي",
        TransManager.workRecord : "سجل العمل",
        TransManager.notifications : "الإشعارات",
        TransManager.orders : "الطلبات",
        TransManager.home : "الشاشة الرئيسة",
        TransManager.acceptAndGo : "تولي المهمة وانطلاق",
        TransManager.estimatedTime : "الوقت المتوقع",
        TransManager.distance : "المسافة",
        TransManager.minute : "دقائق",
        TransManager.km : "كم",
        TransManager.orders_ : "طلبات",
        TransManager.currentNumberOfOrders : "عدد الطلبات الحالية",
        TransManager.completed : "أُتمت بنجاح",
        TransManager.completedOrdersCount : "عدد الطلبات المنجزة",
        TransManager.canceledOrdersCount : "عدد الطلبات التي ألغيتها",
        TransManager.myProfile : "حسابي الشخصي",
        TransManager.saveChanges : "حفظ التغييرات",
        TransManager.myCar : "سيارتي",
        TransManager.achievements : "أوسمة",
        TransManager.settings : "الإعدادات",
        TransManager.helpAndSupportCenter : "مركز الدعم والمساعدة",
        TransManager.aboutUs : "من نحن",
        TransManager.profits : "أرباحي",
        TransManager.logout : "تسجيل الخروج",
        TransManager.changePassword : "تغيير كلمة المرور",
        TransManager.arabic : "العربية",
        TransManager.english : "الإنجليزية",
        TransManager.darkMode : "الوضع المظلم",
        TransManager.lightMode : "الوضع الفاتح",
        TransManager.systemMode : "وضع النظام (تلقائي)",
        TransManager.sessionExpired : "انتهت صلاحية الجلسة، الرجاء تسجيل الدخول",
        TransManager.ownedAchievementsCount : "عدد الأوسمة المملوكة",
        TransManager.send : "ارسال",
        TransManager.currentPassword : "كلمة المرور الحالية",
        TransManager.currentPasswordIsRequired : "أدخل كلمة المرور الحالية",
        TransManager.financialAction : "إجراء مالي",
        TransManager.balance : "الرصيد المتوفر",
        TransManager.accountStatment : "كشف الحساب",
        TransManager.balanceWithdrawalRequest : "طلب سحب الرصيد",
        TransManager.achievementsDetails : "تفاصيل الأوسمة",
        TransManager.securityAndPrivacy : "الامان والخصوصية",
        TransManager.language : "لغة التطبيق",
        TransManager.theme : "مظهر التطبيق",
        TransManager.howCanWeHelpYou : "كيف يمكننا مساعدتك؟",
        TransManager.weAreHereAllTheTimeToMeetYourWishesAndSolveYourProblems : "نتواجد هنا في كل وقت لتلبية رغباتك وحل مشاكلك",
        TransManager.topicTitle : "عنوان الموضوع",
        TransManager.topic : "الموضوع",
        TransManager.writeTopicHere : "اكتب الموضوع هنا...",
        TransManager.topicIsRequired : "الموضوع مطلوب",
        TransManager.topicTitleIsRequired : "عنوان الموضوع مطلوب",
        TransManager.endTrip : "انهاء الرحلة",
        TransManager.startTrip : "بدء الرحلة",
        TransManager.cancel : "الغاء الطلب",
        TransManager.imArrived : "لقد وصلت!",
        TransManager.tripDetails : "تفاصيل الطلب",
      };
}
