import 'package:sarahah_questions/app/localization/trans_manager.dart';

class En implements TransManager {
  static final En singleton = En._internal();
  En._internal();
  Map<String, String> get keys => {
        TransManager.thereIsNoOptionsFound: "There is no options found",
        TransManager.loading: "Loading...",
        TransManager.login: "Login",
        TransManager.username: "Username",
        TransManager.password: "Password",
        TransManager.dontHaveRehlaAccount: "Don`t have Rehla account?",
        TransManager.createNewAccount: "Create account",
        TransManager.rememberMe: "Remember me",
        TransManager.forgotPassword: "Forgot password?",
        TransManager.firstName: "First name",
        TransManager.middleName: "Middle name",
        TransManager.lastName: "Last name",
        TransManager.phoneNumber: "Phone number",
        TransManager.next: "Next",
        TransManager.iHaveRehlaAccount: "I have Rehla account",
        TransManager.dateOfBirth: "Date of Birth",
        TransManager.selectDateOfBirth: "Select date of Birth",
        TransManager.gender: "Gender",
        TransManager.selectYourGender: "Select your gender",
        TransManager.idNumber: "ID number",
        TransManager.drivingLicenseNumber: "Driving license number",
        TransManager.carNumber: "Car number",
        TransManager.carBrand: "Car brand",
        TransManager.selectCarBrand: "Select car brand",
        TransManager.carModel: "Car model",
        TransManager.selectCarModel: "Select car model",
        TransManager.carColor: "Car color",
        TransManager.selectCarColor: "Select car color",
        TransManager.emailAddress: "Email address",
        TransManager.personalPicture: "Personal picture",
        TransManager.idPhoto: "ID card photo",
        TransManager.uploadAphotoOfYourId: "Upload an image of your ID",
        TransManager.drivingLicenseImage: "Driving license image",
        TransManager.uploadAphotoOfYourDrivingLicense:
            "Upload an image of your driving license",
        TransManager.enterYourFirstName: "Enter your first name",
        TransManager.middleNameIsRequired: "Middle name is required",
        TransManager.enterYourLastName: "Enter your last name",
        TransManager.invalidPhoneNumber: "Invalid phone number",
        TransManager.gallery: "Gallery",
        TransManager.camera: "Camera",
        TransManager.pickImage: "Pick image",
        TransManager.invalidEmail: "Invalid email address",
        TransManager.weakPassword: "Weak password",
        TransManager.invalidUsername: "Invalid username",
        TransManager.resetPassword: "Reset password",
        TransManager.resetPasswordHintPart1:
            "Please enter your email address to complete the ",
        TransManager.resetPasswordHintPart2: "password change ",
        TransManager.resetPasswordHintPart3: "process",
        TransManager.continue_: "Continue",
        TransManager.iHaveRememberedMyPassword: "I have remembered my password",
        TransManager.pleaseWait: "Please wait...",
        TransManager.verifyIdentity: "Verify identity",
        TransManager.verifyIdentityHintPart1: "Please enter the ",
        TransManager.verifyIdentityHintPart2: "6-digit ",
        TransManager.verifyIdentityHintPart3:
            "code sent to your email address correctly",
        TransManager.resendCode: "Resend code",
        TransManager.createNewPassword: "Create a new passwor",
        TransManager.createNewPasswordHintPart1:
            "Create a new password, A strong password is typically at least ",
        TransManager.createNewPasswordHintPart2: "8 characters ",
        TransManager.createNewPasswordHintPart3:
            "long and contains a mix of letters, symbols, and numbers",
        TransManager.newPassword: "New password",
        TransManager.confirmNewPassword: "Confirm new password",
        TransManager.yourNewPasswordHasBeenSetSuccessfully:
            "Your new password has been set successfully",
        TransManager.thisFieldRequired: "This field required",
        TransManager.underReview: "Under review",
        TransManager.accountUnderReviewHint:
            "Your account is under review. We will notify you of the results as soon as possible.\n Have a nice day!",
        TransManager.congratulations: "Congratulations",
        TransManager.accountAcceptedHint:
            "Your account on the Reyada platform has been accepted, and you now have full privileges on your account.",
        TransManager.sorry: "Sorry!",
        TransManager.accountRejectedHint:
            "Your account on the Reyada platform has been rejected. Please review the reason for rejection that was sent to you.",
        TransManager.male: "Male",
        TransManager.female: "Female",
        TransManager.twoPasswordsDoesNotMatch: "Two passwords does not match",
        TransManager.pleaseEnterValidEmail: "Please enter valid email",
        TransManager.requiredField: "Required field",
        TransManager.passwordMustBeAtLeast6Characters:
            "Password must be at least 6 characters",
        TransManager.pleaseEnterValidId: "Please enter valid ID",
        TransManager.pleaseEnterValidDateOfBirth:
            "Please enter valid date of birth",
        TransManager.pleaseEnterValidName: "Please enter valid name",
        TransManager.pleaseEnterValidMobile: "Please enter valid mobile",
        TransManager.pleaseEnterValidEmailOrMobile:
            "Please enter valid email or mobile",
        TransManager.pleaseEnterValidLink: "Please enter valid link",
        TransManager.myWallet : "My wallet",
        TransManager.workRecord : "Work record",
        TransManager.notifications : "Notifications",
        TransManager.orders : "Orders",
        TransManager.home : "Home",
        TransManager.acceptAndGo : "Accept and go",
        TransManager.estimatedTime : "Estimated Time",
        TransManager.distance : "Distance",
        TransManager.minute : "minute",
        TransManager.km : "KM",
        TransManager.orders_ : "Orders",
        TransManager.currentNumberOfOrders : "Current Number of Orders",
        TransManager.completed : "Completed",
        TransManager.completedOrdersCount : "Completed orders count",
        TransManager.canceledOrdersCount : "Canceled orders count",
        TransManager.myProfile : "My profile",
        TransManager.saveChanges : "Save changes",
        TransManager.myCar : "My car",
        TransManager.achievements : "Achievements",
        TransManager.settings : "Settings",
        TransManager.helpAndSupportCenter : "Help and support center",
        TransManager.aboutUs : "About us",
        TransManager.profits : "Profits",
        TransManager.logout : "Logout",
        TransManager.changePassword : "Change password",
        TransManager.arabic : "Arabic",
        TransManager.english : "English",
        TransManager.darkMode : "Dark mode",
        TransManager.lightMode : "Light mode",
        TransManager.systemMode : "System mode",
        TransManager.sessionExpired : "Session expired",
        TransManager.ownedAchievementsCount : "Owned achievements count",
        TransManager.send : "Send",
        TransManager.currentPassword : "Current password",
        TransManager.currentPasswordIsRequired : "Current password is required",
        TransManager.financialAction : "Financial action",
        TransManager.balance : "Balance",
        TransManager.accountStatment : "Account statment",
        TransManager.balanceWithdrawalRequest : "Withdraw request",
        TransManager.achievementsDetails : "Achievements details",
        TransManager.securityAndPrivacy : "Security and privacy",
        TransManager.language : "Language",
        TransManager.theme : "Theme",
        TransManager.howCanWeHelpYou : "How can we help you?",
        TransManager.weAreHereAllTheTimeToMeetYourWishesAndSolveYourProblems : "We are here all the time to meet your wishes and solve your problems",
        TransManager.topicTitle : "Topic title",
        TransManager.topic : "Topic",
        TransManager.writeTopicHere : "write topic here...",
        TransManager.topicIsRequired : "Topic is required",
        TransManager.topicTitleIsRequired : "Topic title is required",
        TransManager.endTrip : "End trip",
        TransManager.startTrip : "Start trip",
        TransManager.cancel : "Cancel",
        TransManager.imArrived : "I'm arrived",
        TransManager.tripDetails : "Trip details",
      };
}
